apiVersion: v1
kind: Pod
metadata:
  name: airbyte-secrets-migration
  namespace: ab
spec:
  containers:
    - name: airbyte-secrets-migration
      image: airbyte/secrets-migration:dev
      env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-airbyte-secrets
              key: DATABASE_PASSWORD
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: dev-airbyte-secrets
              key: DATABASE_URL
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: dev-airbyte-secrets
              key: DATABASE_USER
        - name: SECRET_PERSISTENCE
          value: GOOGLE_SECRET_MANAGER
        - name: SECRET_STORE_GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: dev-airbyte-secrets
              key: SECRET_STORE_GCP_PROJECT_ID
        - name: SECRET_STORE_GCP_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: dev-airbyte-secrets
              key: SECRET_STORE_GCP_CREDENTIALS
  restartPolicy: Never
