connector_image: airbyte/source-amazon-seller-partner:dev
tests:
  spec:
    - spec_path: "integration_tests/spec.json"
      backward_compatibility_tests_config:
          disable_for_version: "0.2.27"
  connection:
    # - config_path: "secrets/config.json"
    #   status: "succeed"
    #   timeout_seconds: 60
    - config_path: "integration_tests/invalid_config.json"
      status: "failed"
      timeout_seconds: 60
  discovery:
    - config_path: "secrets/config.json"
      backward_compatibility_tests_config:
          disable_for_version: "0.2.27"
# TODO: uncomment when at least one record exist
#  basic_read:
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog.json"
#      empty_streams:
#        [
#          "Orders",
#          "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL",
#          "GET_MERCHANT_LISTINGS_ALL_DATA",
#          "GET_FBA_INVENTORY_AGED_DATA",
#          "GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL",
#          "GET_FLAT_FILE_OPEN_LISTINGS_DATA",
#          "GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA",
#          "GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA",
#          "GET_VENDOR_INVENTORY_HEALTH_AND_PLANNING_REPORT",
#          "VendorDirectFulfillmentShipping",
#          "GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA",
#          "GET_FBA_FULFILLMENT_CURRENT_INVENTORY_DATA",
#          "GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_PROMOTION_DATA",
#          "GET_FBA_FULFILLMENT_INVENTORY_ADJUSTMENTS_DATA",
#          "GET_FBA_FULFILLMENT_INVENTORY_HEALTH_DATA",
#          "GET_FBA_FULFILLMENT_INVENTORY_RECEIPTS_DATA",
#          "GET_FBA_FULFILLMENT_INVENTORY_SUMMARY_DATA",
#          "GET_FBA_FULFILLMENT_MONTHLY_INVENTORY_DATA",
#          "GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA",
#          "GET_FBA_SNS_FORECAST_DATA",
#          "GET_FBA_SNS_PERFORMANCE_DATA",
#          "GET_FLAT_FILE_ARCHIVED_ORDERS_DATA_BY_ORDER_DATE",
#          "GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE",
#          "GET_MERCHANT_CANCELLED_LISTINGS_DATA",
#          "GET_MERCHANT_LISTINGS_DATA",
#          "GET_MERCHANT_LISTINGS_DATA_BACK_COMPAT",
#          "GET_MERCHANTS_LISTINGS_FYP_REPORT",
#          "GET_MERCHANT_LISTINGS_INACTIVE_DATA",
#          "GET_STRANDED_INVENTORY_UI_DATA",
#          "GET_XML_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL",
#          "GET_LEDGER_DETAIL_VIEW_DATA",
#        ]
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog_brand_analytics_alternate_purchase.json"
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog_brand_analytics_item_comparison.json"
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog_brand_analytics_market_basket.json"
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog_brand_analytics_repeat_purchase.json.json"
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog_brand_analytics_search_terms.json"
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog_fba_fulfillment_customer_shipment_replacement_data.json"
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog_browse_tree_data.json"
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog_restock_inventory.json"
# TODO: uncomment when Orders (or any other incremental) stream is filled with data
#  incremental:
#   - config_path: "secrets/config.json"
#     configured_catalog_path: "integration_tests/configured_catalog.json"
#     future_state_path: "integration_tests/future_state.json"
#     cursor_paths:
#       Orders: ["LastUpdateDate"]
#  full_refresh:
#   - config_path: "secrets/config.json"
#     configured_catalog_path: "integration_tests/configured_catalog.json"
